version: '3'

services:

  influxdb:
    image: influxdb:1.8
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"

  nginx-geo-analyzer:
    image: liangrunda/nginx-geo-analyzer:latest
    volumes:
      - ./geodb:/app/geodb
      - /opt/homebrew/Cellar/nginx/1.27.2/log:/var/log/nginx
    environment:
      - INFLUX_HOST=influxdb
      - LOG_LEVEL=DEBUG
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:11.2.2
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

volumes:
  influxdb-data: 
  grafana-data:
